baseURL = 'https://objectifdigital.ch'
languageCode = 'fr'
title = 'Objectif Digital'
theme = 'PaperMod'

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30


[params.homeInfoParams]
Title = "Hi there ðŸ‘‹"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "facebook"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[params]
description = "Objectif Digital : CrÃ©ation de site internet"
keywords = [ "CrÃ©ation site internet", "Objectif Digital" ]
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
env = "production"
canonicalURL = true
ShowCanonicalLink = true


[params.cover]
responsiveImages = false
